export const packages = [
  {
    title: "Wild offer",
    price: "from 999,-",
    type: "wild",
    subtitle: "Half board and welcome drink",
    description: "Kurzulaub im Herzen von Skagen",
    saveUp: 112,
    additionalInfo: "studio for 2",
    days: [2, 3, 4, 5],
    options: [
      { name: "Overnight stay incl. breakfast", quantity: "1" },
      { name: "Fish buffet", quantity: "1" },
      { name: "Flammkuchen", quantity: "1" },
      { name: "Wine to share per dinner", quantity: "1" },
      { name: "Internet and parking", quantity: "infinity" },
    ],
  },
  {
    title: "Classic package",
    price: "from 1112,-",
    type: "classic",
    subtitle: "Half board and welcome drink",
    description: "Kurzulaub im Herzen von Skagen",
    saveUp: 188,
    additionalInfo: "double room",
    days: [2, 3, 4, 5, "More"],
    options: [
      { name: "Overnight stay incl. breakfast", quantity: "1" },
      { name: "Fish buffet", quantity: "1" },
      { name: "Flammkuchen", quantity: "1" },
      { name: "Wine to share per dinner", quantity: "1" },
      { name: "Internet and parking", quantity: "infinity" },
    ],
  },
  {
    title: "Quality time",
    price: "from 1288,-",
    type: "quality",
    subtitle: "Half board and welcome drink",
    description: "Kurzulaub im Herzen von Skagen",
    saveUp: 204,
    additionalInfo: "double room",
    days: [2, 3, 4, 5, "More"],
    options: [
      { name: "Overnight stay incl. breakfast", quantity: "1" },
      { name: "Fish buffet", quantity: "1" },
      { name: "Flammkuchen", quantity: "1" },
      { name: "Wine to share per dinner", quantity: "1" },
      { name: "Internet and parking", quantity: "infinity" },
    ],
  },
];
